query($owner: String!, $name: String!, $since: DateTime!) {
  repository(owner: $owner, name: $name) {
    issues(filterBy: { since: $since }, last: 50) {
      nodes {
        id
        number
        title
        databaseId
      }
      pageInfo {
        ...pageInfoFields
      }
    }
    pullRequests(last: 50) {
      nodes {
        id
        number
        title
        databaseId
      }
      pageInfo {
        ...pageInfoFields
      }
    }
  }
}

fragment pageInfoFields on PageInfo {
  hasNextPage
  startCursor
  endCursor
}
